name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:

  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: install deps
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          sudo apt-get update
          sudo apt-get -o Acquire::Retries=3 install make ftp git bzr curl wget -y && sudo apt upgrade -y
          make deps

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.2
          golangci-lint run --timeout 10m

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make build

    - name: Run Test
        run:  make test