name: go-fvm-sdk
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
env:
  RUSTFLAGS: -Dwarnings

jobs:

  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          targets: wasm32-unknown-unknown

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get -o Acquire::Retries=3 install make ftp git bzr curl wget -y && sudo apt upgrade -y

      - name: install tinygo
        run: |
          wget -q https://github.com/ipfs-force-community/tinygo/releases/download/fvm%400.0.1/tinygo-linux-ubuntu-20.04
          mkdir bin
          mv tinygo-linux-ubuntu-20.04 bin/tinygo
          chmod 777 bin/tinygo
          export PATH=$PATH:${{github.workspace}}/bin
          tinygo version

      - name: Build
        run: |
          make build

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.2
          golangci-lint run --timeout 10m

      - name: Test
        run:  make test